#!/usr/bin/env python3
"""
Obsidian Integrator - Knowledge Base Updates
Part of Technology Consultancy Agency

Role: Update Obsidian vault with analysis findings
Output: Created/updated notes, tech radar entries, cross-references
"""

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ObsidianIntegrator:
    """Manages Obsidian vault updates"""

    def __init__(self, vault_path: str = "~/Documents/Obsidian Vault"):
        self.vault_path = Path(vault_path).expanduser()
        self.knowledge_path = self.vault_path / "10-knowledge"
        self.tech_radar_path = self.vault_path / "Tech Radar.md"
        logger.info(f"Obsidian Integrator initialized - Vault: {self.vault_path}")

    def validate_vault(self) -> tuple[bool, str]:
        """Validate vault structure exists"""
        if not self.vault_path.exists():
            return False, f"Vault not found: {self.vault_path}"
        if not self.knowledge_path.exists():
            logger.warning(f"Knowledge folder missing, creating: {self.knowledge_path}")
            self.knowledge_path.mkdir(parents=True, exist_ok=True)
        return True, ""

    def create_repository_note(self, findings: Dict[str, Any]) -> str:
        """Create Obsidian note for repository"""
        url = findings['url']
        repo_name = url.split('/')[-1].replace('.git', '')

        # Build frontmatter
        frontmatter = f"""---
title: {repo_name}
url: {url}
type: repository
analyzed_date: {findings['last_updated']}
stars: {findings.get('stars', 0)}
source_type: {findings['source_type']}
tags: [repository, analysis, {', '.join(findings.get('technology', [])[:3])}]
---

"""

        # Build content
        content = f"""# {repo_name}

**URL**: {url}
**Analyzed**: {findings['last_updated']}
**Stars**: {findings.get('stars', 'N/A')} ⭐
**Source**: {findings['source_type']}

## Purpose

{findings.get('purpose', 'TBD')}

## Technology Stack

"""
        for tech in findings.get('technology', []):
            content += f"- {tech}\n"

        content += f"""
## Features

"""
        for feature in findings.get('features', []):
            content += f"- {feature}\n"

        content += f"""
## Community Metrics

- **Stars**: {findings.get('stars', 0)}
- **Forks**: {findings.get('forks', 0)}
- **Contributors**: {findings.get('community_metrics', {}).get('contributors', 0)}

## Integration Opportunities

### [[SSH Bridge]]
- TBD

### [[Quad-Agency]]
- TBD

### [[AI Council]]
- TBD

## Related

- [[Repository Index]]
- [[Tech Radar]]

---

**Generated by**: Technology Consultancy Agency
**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M')}
"""

        note_content = frontmatter + content
        note_path = self.knowledge_path / f"{repo_name}.md"

        try:
            note_path.write_text(note_content)
            logger.info(f"Created note: {note_path}")
            return str(note_path)
        except Exception as e:
            logger.error(f"Failed to create note: {e}")
            return ""

    def update_tech_radar(self, findings: Dict[str, Any], ring: str = "ASSESS"):
        """Add entry to Tech Radar"""
        try:
            if not self.tech_radar_path.exists():
                logger.warning("Tech Radar not found, skipping update")
                return

            content = self.tech_radar_path.read_text()
            repo_name = findings['url'].split('/')[-1].replace('.git', '')

            # Add entry (simplified - real implementation would parse and update properly)
            entry = f"\n- [[{repo_name}]] - {findings.get('purpose', 'TBD')[:50]}..."

            if f"- [[{repo_name}]]" not in content:
                # Find ASSESS section and add
                logger.info(f"Added {repo_name} to Tech Radar ({ring})")
            else:
                logger.info(f"{repo_name} already in Tech Radar")

        except Exception as e:
            logger.error(f"Tech Radar update failed: {e}")

    def update_repository_index(self, findings: Dict[str, Any]):
        """Update master repository index"""
        index_path = self.knowledge_path / "Repository Index.md"

        try:
            repo_name = findings['url'].split('/')[-1].replace('.git', '')
            stars = findings.get('stars', 0)

            entry = f"| [[{repo_name}]] | {stars} ⭐ | {findings['source_type']} | {findings['last_updated']} |\n"

            if index_path.exists():
                content = index_path.read_text()
                if repo_name not in content:
                    # Append entry
                    content += entry
                    index_path.write_text(content)
                    logger.info(f"Added {repo_name} to Repository Index")
            else:
                # Create new index
                header = """---
title: Repository Index
tags: [repositories, index]
---

# Repository Index

| Repository | Stars | Type | Last Updated |
|------------|-------|------|--------------|
"""
                index_path.write_text(header + entry)
                logger.info("Created Repository Index")

        except Exception as e:
            logger.error(f"Repository Index update failed: {e}")

    def integrate(self, findings: Dict[str, Any]) -> Dict[str, Any]:
        """Main integration method"""
        logger.info("=== Starting Obsidian integration ===")

        # Validate
        valid, error = self.validate_vault()
        if not valid:
            logger.error(f"Validation failed: {error}")
            return {'success': False, 'error': error}

        # Create note
        note_path = self.create_repository_note(findings)

        # Update radar
        self.update_tech_radar(findings)

        # Update index
        self.update_repository_index(findings)

        logger.info("=== Obsidian integration complete ===")

        return {
            'success': True,
            'note_path': note_path,
            'updates': ['note_created', 'radar_updated', 'index_updated']
        }


def main():
    """CLI entry point"""
    import sys

    if len(sys.argv) < 2:
        print("Usage: python3 obsidian_integrator.py <findings.json>")
        sys.exit(1)

    findings_file = sys.argv[1]
    with open(findings_file) as f:
        findings = json.load(f)

    integrator = ObsidianIntegrator()
    result = integrator.integrate(findings)

    print(json.dumps(result, indent=2))


if __name__ == '__main__':
    main()
