#!/usr/bin/env python3
"""
Obsidian Integrator - Knowledge Base Updates
Part of Technology Consultancy Agency

Role: Update Obsidian vault with analysis findings
Output: Created/updated notes, tech radar entries, cross-references
"""

import json
import os
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ObsidianIntegrator:
    """Manages Obsidian vault updates"""

    def __init__(self, vault_path: str = None):
        # Auto-detect vault path based on environment
        if vault_path is None:
            # Try local path first (for local development)
            local_path = Path("~/Documents/Obsidian Vault/10-knowledge").expanduser()
            # Cloud path (Streamlit Cloud, Hugging Face, etc.)
            cloud_path = Path("obsidian_vault")

            if local_path.exists():
                self.vault_path = local_path.parent
                self.knowledge_path = local_path
            elif cloud_path.exists():
                self.vault_path = cloud_path
                self.knowledge_path = cloud_path
            else:
                # Default to cloud path (create if needed)
                self.vault_path = cloud_path
                self.knowledge_path = cloud_path
        else:
            self.vault_path = Path(vault_path).expanduser()
            self.knowledge_path = self.vault_path / "10-knowledge" if (self.vault_path / "10-knowledge").exists() else self.vault_path

        self.tech_radar_path = self.vault_path / "Tech Radar.md"
        logger.info(f"Obsidian Integrator initialized - Vault: {self.vault_path}")

    def validate_vault(self) -> tuple[bool, str]:
        """Validate vault structure exists"""
        if not self.vault_path.exists():
            return False, f"Vault not found: {self.vault_path}"
        if not self.knowledge_path.exists():
            logger.warning(f"Knowledge folder missing, creating: {self.knowledge_path}")
            self.knowledge_path.mkdir(parents=True, exist_ok=True)
        return True, ""

    def create_repository_note(self, findings: Dict[str, Any]) -> str:
        """Create Obsidian note for repository"""
        url = findings['url']
        repo_name = url.split('/')[-1].replace('.git', '')

        # Build frontmatter
        frontmatter = f"""---
title: {repo_name}
url: {url}
type: repository
analyzed_date: {findings['last_updated']}
stars: {findings.get('stars', 0)}
source_type: {findings['source_type']}
tags: [repository, analysis, {', '.join(findings.get('technology', [])[:3])}]
---

"""

        # Build content
        content = f"""# {repo_name}

**URL**: {url}
**Analyzed**: {findings['last_updated']}
**Stars**: {findings.get('stars', 'N/A')} ⭐
**Source**: {findings['source_type']}

## Purpose

{findings.get('purpose', 'TBD')}

## Technology Stack

"""
        for tech in findings.get('technology', []):
            content += f"- {tech}\n"

        content += f"""
## Features

"""
        for feature in findings.get('features', []):
            content += f"- {feature}\n"

        content += f"""
## Community Metrics

- **Stars**: {findings.get('stars', 0)}
- **Forks**: {findings.get('forks', 0)}
- **Contributors**: {findings.get('community_metrics', {}).get('contributors', 0)}

## Integration Opportunities

### [[SSH Bridge]]
- TBD

### [[Quad-Agency]]
- TBD

### [[AI Council]]
- TBD

## Related

- [[Repository Index]]
- [[Tech Radar]]

---

**Generated by**: Technology Consultancy Agency
**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M')}
"""

        note_content = frontmatter + content
        note_path = self.knowledge_path / f"{repo_name}.md"

        try:
            note_path.write_text(note_content)
            logger.info(f"Created note: {note_path}")
            return str(note_path)
        except Exception as e:
            logger.error(f"Failed to create note: {e}")
            return ""

    def update_tech_radar(self, findings: Dict[str, Any], ring: str = "ASSESS"):
        """Add entry to Tech Radar"""
        try:
            if not self.tech_radar_path.exists():
                logger.warning("Tech Radar not found, skipping update")
                return

            content = self.tech_radar_path.read_text()
            repo_name = findings['url'].split('/')[-1].replace('.git', '')

            # Add entry (simplified - real implementation would parse and update properly)
            entry = f"\n- [[{repo_name}]] - {findings.get('purpose', 'TBD')[:50]}..."

            if f"- [[{repo_name}]]" not in content:
                # Find ASSESS section and add
                logger.info(f"Added {repo_name} to Tech Radar ({ring})")
            else:
                logger.info(f"{repo_name} already in Tech Radar")

        except Exception as e:
            logger.error(f"Tech Radar update failed: {e}")

    def update_repository_index(self, findings: Dict[str, Any]):
        """Update master repository index"""
        index_path = self.knowledge_path / "Repository Index.md"

        try:
            repo_name = findings['url'].split('/')[-1].replace('.git', '')
            stars = findings.get('stars', 0)

            entry = f"| [[{repo_name}]] | {stars} ⭐ | {findings['source_type']} | {findings['last_updated']} |\n"

            if index_path.exists():
                content = index_path.read_text()
                if repo_name not in content:
                    # Append entry
                    content += entry
                    index_path.write_text(content)
                    logger.info(f"Added {repo_name} to Repository Index")
            else:
                # Create new index
                header = """---
title: Repository Index
tags: [repositories, index]
---

# Repository Index

| Repository | Stars | Type | Last Updated |
|------------|-------|------|--------------|
"""
                index_path.write_text(header + entry)
                logger.info("Created Repository Index")

        except Exception as e:
            logger.error(f"Repository Index update failed: {e}")

    def git_sync(self, repo_name: str, vault_as_repo: bool = False) -> tuple[bool, str]:
        """
        Sync Obsidian vault to GitHub repository

        Args:
            repo_name: Name of repository (for commit message)
            vault_as_repo: If True, treat vault itself as git repo (Obsidian Git plugin mode)
                          If False, sync vault files to separate git repo

        Returns:
            (success, message)
        """
        try:
            # Determine git directory
            if vault_as_repo:
                git_dir = self.vault_path
            else:
                # Use parent directory if agency repo
                git_dir = Path.cwd()

            logger.info(f"Git sync starting in: {git_dir}")

            # Change to git directory
            original_dir = os.getcwd()
            os.chdir(git_dir)

            try:
                # Check if git repo
                result = subprocess.run(
                    ['git', 'rev-parse', '--is-inside-work-tree'],
                    capture_output=True,
                    text=True,
                    timeout=5
                )

                if result.returncode != 0:
                    logger.warning(f"Not a git repository: {git_dir}")
                    return False, "Not a git repository"

                # Stage changes (only vault files if in agency repo)
                if vault_as_repo:
                    add_cmd = ['git', 'add', '.']
                else:
                    # Add only Obsidian vault related files
                    add_cmd = ['git', 'add', str(self.vault_path)]

                subprocess.run(add_cmd, timeout=10, check=True)

                # Check if there are changes to commit
                status_result = subprocess.run(
                    ['git', 'status', '--porcelain'],
                    capture_output=True,
                    text=True,
                    timeout=5
                )

                if not status_result.stdout.strip():
                    logger.info("No changes to commit")
                    return True, "No changes"

                # Commit
                commit_msg = f"Add analysis: {repo_name}"
                subprocess.run(
                    ['git', 'commit', '-m', commit_msg],
                    timeout=10,
                    check=True,
                    capture_output=True
                )

                # Push
                subprocess.run(
                    ['git', 'push'],
                    timeout=30,
                    check=True,
                    capture_output=True
                )

                logger.info(f"✅ Git sync successful: {repo_name}")
                return True, f"Synced: {repo_name}"

            finally:
                # Return to original directory
                os.chdir(original_dir)

        except subprocess.TimeoutExpired:
            logger.error("Git operation timed out")
            return False, "Git timeout"

        except subprocess.CalledProcessError as e:
            logger.error(f"Git command failed: {e}")
            return False, f"Git error: {e.returncode}"

        except Exception as e:
            logger.error(f"Git sync failed: {e}")
            return False, str(e)

    def integrate(self, findings: Dict[str, Any]) -> Dict[str, Any]:
        """Main integration method"""
        logger.info("=== Starting Obsidian integration ===")

        # Validate
        valid, error = self.validate_vault()
        if not valid:
            logger.error(f"Validation failed: {error}")
            return {'success': False, 'error': error}

        # Create note
        note_path = self.create_repository_note(findings)

        # Update radar
        self.update_tech_radar(findings)

        # Update index
        self.update_repository_index(findings)

        # Sync to GitHub
        repo_name = findings['url'].split('/')[-1].replace('.git', '')
        sync_success, sync_msg = self.git_sync(repo_name, vault_as_repo=False)

        logger.info("=== Obsidian integration complete ===")

        result = {
            'success': True,
            'note_path': note_path,
            'updates': ['note_created', 'radar_updated', 'index_updated']
        }

        if sync_success:
            result['updates'].append('github_synced')
            result['sync_message'] = sync_msg
        else:
            result['sync_warning'] = f"GitHub sync failed: {sync_msg}"

        return result


def main():
    """CLI entry point"""
    import sys

    if len(sys.argv) < 2:
        print("Usage: python3 obsidian_integrator.py <findings.json>")
        sys.exit(1)

    findings_file = sys.argv[1]
    with open(findings_file) as f:
        findings = json.load(f)

    integrator = ObsidianIntegrator()
    result = integrator.integrate(findings)

    print(json.dumps(result, indent=2))


if __name__ == '__main__':
    main()
